spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 76a4a5cb969b18ceba29
            clientSecret: c96d5e44a95b4eee1ba3f7a9f577779375921069
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
    provider:
      github:
        authorization-uri: https://github.com/login/oauth/authorize
        token-uri: https://github.com/login/oauth/access_token
        user-info-uri: https://api.github.com/user